#+TITLE: The Wired Protocol

* Decentralization is good
  Decentralization is the heart of the internet, it's what it was intened to be: a
  decentralized network that could survive nuclear attack.

  But the internet lost. Nowadays, everything is centralized. The 3 most visited
  websites account for 50% of the total traffic on the net; this is very
  disappointing, but the expected result of our capitalist society.

* Examples of successful decentralized services
** Bittorrent
   Bittorrent is an example of a truly decentralized protocol. Used to share files,
   it scales very well to modern internet infrastructure. It works by sharing files
   to multiple peers that have the same file, and download it from every person
   that has it.

** Bitcoin
   Bitcoin is even more crazy: a decentralized banking system. It uses a shared
   ledger, RSA signatures and a chain of SHA256: signed blocks. Everyone has to share
   the same ledger, but the ledger should not be centralized. To solve this trust
   problem, bitcoin uses "computational trust", a chain of hashed
   finishing by zeroes.

* The Wired
  The wired wants to be a complete information-sharing protocol, that could result
  in the creation of decentralized "Wireplaces".
  The prototype for this protocol will be a simple imageboard, where you can
  create thread, reply and post images. It will be named "Wirechan"

** High-level overview of the protocol
*** Pinging and connecting to peers
	The protocol must have some way to check if a server is up and
	working, so as to connect to every disponible peer.

	To do that, two things must be implemented: Pinging and Peer
	sharing.
	Pinging is very simple: to check if an host is up, just send
	"WIRED/0.1 PING", and it should answer you: "WIRED/0.1 PONG". If
	it doesn't, it means that you should not connect to this peer.

	Peer sharing is more complicated.
	TODO: Explain why we need a dynamic peers file.
